name: Deploy Prd

on:
    push:
        branches: [main]

jobs:
    deploy:
        if: >-
            contains(fromJson('["OWNER","MEMBER","COLLABORATOR"]'), github.event.sender.author_association)
        uses: mydx-dev/common-workflow/.github/workflows/deploy.yml@v1
        with:
            environment: prd
            clasp_json_secret: CLASP_JSON_PRD
            comment: true
        secrets: inherit
